package com.example.jshir_000.nistbuddy;

import android.app.Activity;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.firebase.client.ChildEventListener;
import com.firebase.client.DataSnapshot;
import com.firebase.client.Firebase;
import com.firebase.client.FirebaseError;
import com.firebase.client.MutableData;
import com.firebase.client.Query;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class constantsButtonActivity extends Activity {

    private Button Button1;
    private TextView textView2;
    private String FirebasePath;
    private EditText SearchText1;
    private String lookupstring;
    private Spinner spinner1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Firebase.setAndroidContext(this);
        setContentView(R.layout.activity_constants_button);
        lookupstring = "hello";


        textView2 = (TextView)findViewById(R.id.textView2);
        spinner1 = (Spinner)findViewById(R.id.spinner1);
        FirebasePath = "https://nist-buddy.firebaseio.com/constants/constant/";

        List list = new ArrayList();

        list.add("{220} lattice spacing of silicon");
        list.add("alpha particle-electron mass ratio");
        list.add("alpha particle mass");
        list.add("alpha particle mass energy equivalent");
        list.add("alpha particle mass energy equivalent in MeV");
        list.add("alpha particle mass in u");
        list.add("alpha particle molar mass");
        list.add("alpha particle-proton mass ratio");
        list.add("Angstrom star");
        list.add("atomic mass constant");
        list.add("atomic mass constant energy equivalent");
        list.add("atomic mass constant energy equivalent in MeV");
        list.add("atomic mass unit-electron volt relationship");
        list.add("atomic mass unit-hartree relationship");
        list.add("atomic mass unit-hertz relationship");
        list.add("atomic mass unit-inverse meter relationship");
        list.add("atomic mass unit-joule relationship");
        list.add("atomic mass unit-kelvin relationship");
        list.add("atomic mass unit-kilogram relationship");
        list.add("atomic unit of 1st hyperpolarizability");
        list.add("atomic unit of 2nd hyperpolarizability");
        list.add("atomic unit of action");
        list.add("atomic unit of charge");
        list.add("atomic unit of charge density");
        list.add("atomic unit of current");
        list.add("atomic unit of electric dipole mom.");
        list.add("atomic unit of electric field");
        list.add("atomic unit of electric field gradient");
        list.add("atomic unit of electric polarizability");
        list.add("atomic unit of electric potential");
        list.add("atomic unit of electric quadrupole mom.");
        list.add("atomic unit of energy");
        list.add("atomic unit of force");
        list.add("atomic unit of length");
        list.add("atomic unit of mag. dipole mom.");
        list.add("atomic unit of mag. flux density");
        list.add("atomic unit of magnetizability");
        list.add("atomic unit of mass");
        list.add("atomic unit of mom.um");
        list.add("atomic unit of permittivity");
        list.add("atomic unit of time");
        list.add("atomic unit of velocity");
        list.add("Avogadro constant");
        list.add("Bohr magneton");
        list.add("Bohr magneton in eV/T");
        list.add("Bohr magneton in Hz/T");
        list.add("Bohr magneton in inverse meters per tesla");
        list.add("Bohr magneton in K/T");
        list.add("Bohr radius");
        list.add("Boltzmann constant");
        list.add("Boltzmann constant in eV/K");
        list.add("Boltzmann constant in Hz/K");
        list.add("Boltzmann constant in inverse meters per kelvin");
        list.add("characteristic impedance of vacuum");
        list.add("classical electron radius");
        list.add("Compton wavelength");
        list.add("Compton wavelength over 2 pi");
        list.add("conductance quantum");
        list.add("conventional value of Josephson constant");
        list.add("conventional value of von Klitzing constant");
        list.add("Cu x unit");
        list.add("deuteron-electron mag. mom. ratio");
        list.add("deuteron-electron mass ratio");
        list.add("deuteron g factor");
        list.add("deuteron mag. mom.");
        list.add("deuteron mag. mom. to Bohr magneton ratio");
        list.add("deuteron mag. mom. to nuclear magneton ratio");
        list.add("deuteron mass");
        list.add("deuteron mass energy equivalent");
        list.add("deuteron mass energy equivalent in MeV");
        list.add("deuteron mass in u");
        list.add("deuteron molar mass");
        list.add("deuteron-neutron mag. mom. ratio");
        list.add("deuteron-proton mag. mom. ratio");
        list.add("deuteron-proton mass ratio");
        list.add("deuteron rms charge radius");
        list.add("electric constant");
        list.add("electron charge to mass quotient");
        list.add("electron-deuteron mag. mom. ratio");
        list.add("electron-deuteron mass ratio");
        list.add("electron g factor");
        list.add("electron gyromag. ratio");
        list.add("electron gyromag. ratio over 2 pi");
        list.add("electron-helion mass ratio");
        list.add("electron mag. mom.");
        list.add("electron mag. mom. anomaly");
        list.add("electron mag. mom. to Bohr magneton ratio");
        list.add("electron mag. mom. to nuclear magneton ratio");
        list.add("electron mass");
        list.add("electron mass energy equivalent");
        list.add("electron mass energy equivalent in MeV");
        list.add("electron mass in u");
        list.add("electron molar mass");
        list.add("electron-muon mag. mom. ratio");
        list.add("electron-muon mass ratio");
        list.add("electron-neutron mag. mom. ratio");
        list.add("electron-neutron mass ratio");
        list.add("electron-proton mag. mom. ratio");
        list.add("electron-proton mass ratio");
        list.add("electron-tau mass ratio");
        list.add("electron to alpha particle mass ratio");
        list.add("electron to shielded helion mag. mom. ratio");
        list.add("electron to shielded proton mag. mom. ratio");
        list.add("electron-triton mass ratio");
        list.add("electron volt");
        list.add("electron volt-atomic mass unit relationship");
        list.add("electron volt-hartree relationship");
        list.add("electron volt-hertz relationship");
        list.add("electron volt-inverse meter relationship");
        list.add("electron volt-joule relationship");
        list.add("electron volt-kelvin relationship");
        list.add("electron volt-kilogram relationship");
        list.add("elementary charge");
        list.add("elementary charge over h");
        list.add("Faraday constant");
        list.add("Faraday constant for conventional electric current");
        list.add("Fermi coupling constant");
        list.add("fine-structure constant");
        list.add("first radiation constant");
        list.add("first radiation constant for spectral radiance");
        list.add("hartree-atomic mass unit relationship");
        list.add("hartree-electron volt relationship");
        list.add("Hartree energy");
        list.add("Hartree energy in eV");
        list.add("hartree-hertz relationship");
        list.add("hartree-inverse meter relationship");
        list.add("hartree-joule relationship");
        list.add("hartree-kelvin relationship");
        list.add("hartree-kilogram relationship");
        list.add("helion-electron mass ratio");
        list.add("helion g factor");
        list.add("helion mag. mom.");
        list.add("helion mag. mom. to Bohr magneton ratio");
        list.add("helion mag. mom. to nuclear magneton ratio");
        list.add("helion mass");
        list.add("helion mass energy equivalent");
        list.add("helion mass energy equivalent in MeV");
        list.add("helion mass in u");
        list.add("helion molar mass");
        list.add("helion-proton mass ratio");
        list.add("hertz-atomic mass unit relationship");
        list.add("hertz-electron volt relationship");
        list.add("hertz-hartree relationship");
        list.add("hertz-inverse meter relationship");
        list.add("hertz-joule relationship");
        list.add("hertz-kelvin relationship");
        list.add("hertz-kilogram relationship");
        list.add("inverse fine-structure constant");
        list.add("inverse meter-atomic mass unit relationship");
        list.add("inverse meter-electron volt relationship");
        list.add("inverse meter-hartree relationship");
        list.add("inverse meter-hertz relationship");
        list.add("inverse meter-joule relationship");
        list.add("inverse meter-kelvin relationship");
        list.add("inverse meter-kilogram relationship");
        list.add("inverse of conductance quantum");
        list.add("Josephson constant");
        list.add("joule-atomic mass unit relationship");
        list.add("joule-electron volt relationship");
        list.add("joule-hartree relationship");
        list.add("joule-hertz relationship");
        list.add("joule-inverse meter relationship");
        list.add("joule-kelvin relationship");
        list.add("joule-kilogram relationship");
        list.add("kelvin-atomic mass unit relationship");
        list.add("kelvin-electron volt relationship");
        list.add("kelvin-hartree relationship");
        list.add("kelvin-hertz relationship");
        list.add("kelvin-inverse meter relationship");
        list.add("kelvin-joule relationship");
        list.add("kelvin-kilogram relationship");
        list.add("kilogram-atomic mass unit relationship");
        list.add("kilogram-electron volt relationship");
        list.add("kilogram-hartree relationship");
        list.add("kilogram-hertz relationship");
        list.add("kilogram-inverse meter relationship");
        list.add("kilogram-joule relationship");
        list.add("kilogram-kelvin relationship");
        list.add("lattice parameter of silicon");
        list.add("Loschmidt constant (273.15 K, 100 kPa)");
        list.add("Loschmidt constant (273.15 K, 101.325 kPa)");
        list.add("mag. constant");
        list.add("mag. flux quantum");
        list.add("molar gas constant");
        list.add("molar mass constant");
        list.add("molar mass of carbon-12");
        list.add("molar Planck constant");
        list.add("molar Planck constant times c");
        list.add("molar volume of ideal gas (273.15 K, 100 kPa)");
        list.add("molar volume of ideal gas (273.15 K, 101.325 kPa)");
        list.add("molar volume of silicon");
        list.add("Mo x unit");
        list.add("muon Compton wavelength");
        list.add("muon Compton wavelength over 2 pi");
        list.add("muon-electron mass ratio");
        list.add("muon g factor");
        list.add("muon mag. mom.");
        list.add("muon mag. mom. anomaly");
        list.add("muon mag. mom. to Bohr magneton ratio");
        list.add("muon mag. mom. to nuclear magneton ratio");
        list.add("muon mass");
        list.add("muon mass energy equivalent");
        list.add("muon mass energy equivalent in MeV");
        list.add("muon mass in u");
        list.add("muon molar mass");
        list.add("muon-neutron mass ratio");
        list.add("muon-proton mag. mom. ratio");
        list.add("muon-proton mass ratio");
        list.add("muon-tau mass ratio");
        list.add("natural unit of action");
        list.add("natural unit of action in eV s");
        list.add("natural unit of energy");
        list.add("natural unit of energy in MeV");
        list.add("natural unit of length");
        list.add("natural unit of mass");
        list.add("natural unit of mom.um");
        list.add("natural unit of mom.um in MeV/c");
        list.add("natural unit of time");
        list.add("natural unit of velocity");
        list.add("neutron Compton wavelength");
        list.add("neutron Compton wavelength over 2 pi");
        list.add("neutron-electron mag. mom. ratio");
        list.add("neutron-electron mass ratio");
        list.add("neutron g factor");
        list.add("neutron gyromag. ratio");
        list.add("neutron gyromag. ratio over 2 pi");
        list.add("neutron mag. mom.");
        list.add("neutron mag. mom. to Bohr magneton ratio");
        list.add("neutron mag. mom. to nuclear magneton ratio");
        list.add("neutron mass");
        list.add("neutron mass energy equivalent");
        list.add("neutron mass energy equivalent in MeV");
        list.add("neutron mass in u");
        list.add("neutron molar mass");
        list.add("neutron-muon mass ratio");
        list.add("neutron-proton mag. mom. ratio");
        list.add("neutron-proton mass difference");
        list.add("neutron-proton mass difference energy equivalent");
        list.add("neutron-proton mass difference energy equivalent in MeV");
        list.add("neutron-proton mass difference in u");
        list.add("neutron-proton mass ratio");
        list.add("neutron-tau mass ratio");
        list.add("neutron to shielded proton mag. mom. ratio");
        list.add("Newtonian constant of gravitation");
        list.add("Newtonian constant of gravitation over h-bar c");
        list.add("nuclear magneton");
        list.add("nuclear magneton in eV/T");
        list.add("nuclear magneton in inverse meters per tesla");
        list.add("nuclear magneton in K/T");
        list.add("nuclear magneton in MHz/T");
        list.add("Planck constant");
        list.add("Planck constant in eV s");
        list.add("Planck constant over 2 pi");
        list.add("Planck constant over 2 pi in eV s");
        list.add("Planck constant over 2 pi times c in MeV fm");
        list.add("Planck length");
        list.add("Planck mass");
        list.add("Planck mass energy equivalent in GeV");
        list.add("Planck temperature");
        list.add("Planck time");
        list.add("proton charge to mass quotient");
        list.add("proton Compton wavelength");
        list.add("proton Compton wavelength over 2 pi");
        list.add("proton-electron mass ratio");
        list.add("proton g factor");
        list.add("proton gyromag. ratio");
        list.add("proton gyromag. ratio over 2 pi");
        list.add("proton mag. mom.");
        list.add("proton mag. mom. to Bohr magneton ratio");
        list.add("proton mag. mom. to nuclear magneton ratio");
        list.add("proton mag. shielding correction");
        list.add("proton mass");
        list.add("proton mass energy equivalent");
        list.add("proton mass energy equivalent in MeV");
        list.add("proton mass in u");
        list.add("proton molar mass");
        list.add("proton-muon mass ratio");
        list.add("proton-neutron mag. mom. ratio");
        list.add("proton-neutron mass ratio");
        list.add("proton rms charge radius");
        list.add("proton-tau mass ratio");
        list.add("quantum of circulation");
        list.add("quantum of circulation times 2");
        list.add("Rydberg constant");
        list.add("Rydberg constant times c in Hz");
        list.add("Rydberg constant times hc in eV");
        list.add("Rydberg constant times hc in J");
        list.add("Sackur-Tetrode constant (1 K, 100 kPa)");
        list.add("Sackur-Tetrode constant (1 K, 101.325 kPa)");
        list.add("second radiation constant");
        list.add("shielded helion gyromag. ratio");
        list.add("shielded helion gyromag. ratio over 2 pi");
        list.add("shielded helion mag. mom.");
        list.add("shielded helion mag. mom. to Bohr magneton ratio");
        list.add("shielded helion mag. mom. to nuclear magneton ratio");
        list.add("shielded helion to proton mag. mom. ratio");
        list.add("shielded helion to shielded proton mag. mom. ratio");
        list.add("shielded proton gyromag. ratio");
        list.add("shielded proton gyromag. ratio over 2 pi");
        list.add("shielded proton mag. mom.");
        list.add("shielded proton mag. mom. to Bohr magneton ratio");
        list.add("shielded proton mag. mom. to nuclear magneton ratio");
        list.add("speed of light in vacuum");
        list.add("standard acceleration of gravity");
        list.add("standard atmosphere");
        list.add("standard-state pressure");
        list.add("Stefan-Boltzmann constant");
        list.add("tau Compton wavelength");
        list.add("tau Compton wavelength over 2 pi");
        list.add("tau-electron mass ratio");
        list.add("tau mass");
        list.add("tau mass energy equivalent");
        list.add("tau mass energy equivalent in MeV");
        list.add("tau mass in u");
        list.add("tau molar mass");
        list.add("tau-muon mass ratio");
        list.add("tau-neutron mass ratio");
        list.add("tau-proton mass ratio");
        list.add("Thomson cross section");
        list.add("triton-electron mass ratio");
        list.add("triton g factor");
        list.add("triton mag. mom.");
        list.add("triton mag. mom. to Bohr magneton ratio");
        list.add("triton mag. mom. to nuclear magneton ratio");
        list.add("triton mass");
        list.add("triton mass energy equivalent");
        list.add("triton mass energy equivalent in MeV");
        list.add("triton mass in u");
        list.add("triton molar mass");
        list.add("triton-proton mass ratio");
        list.add("unified atomic mass unit");
        list.add("von Klitzing constant");
        list.add("weak mixing angle");
        list.add("Wien frequency displacement law constant");
        list.add("Wien wavelength displacement law constant");


        ArrayAdapter dataAdapter = new ArrayAdapter(this,android.R.layout.simple_spinner_item, list);
        dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);


        spinner1.setAdapter(dataAdapter);

        spinner1.setOnItemSelectedListener(new onThermocoupleCoeffsItemSelectedListener() {

            public void onItemSelected(AdapterView parent, View view, int pos, long id) {

                        switch (pos) {
                            case 0: lookupstring = "{220} lattice spacing of silicon";break;
                            case 1: lookupstring = "alpha particle-electron mass ratio"; break;
                            case 2: lookupstring = "alpha particle mass";break;
                            case 3: lookupstring = "alpha particle mass energy equivalent";break;
                            case 4:  lookupstring ="alpha particle mass energy equivalent in MeV"; break;
                            case 5:  lookupstring ="alpha particle mass in u"; break;
                            case 6:  lookupstring ="alpha particle molar mass"; break;
                            case 7:  lookupstring ="alpha particle-proton mass ratio"; break;
                            case 8:  lookupstring ="Angstrom star"; break;
                            case 9:  lookupstring ="atomic mass constant"; break;
                            case 10:  lookupstring ="atomic mass constant energy equivalent"; break;
                            case 11:  lookupstring ="atomic mass constant energy equivalent in MeV"; break;
                            case 12:  lookupstring ="atomic mass unit-electron volt relationship"; break;
                            case 13:  lookupstring ="atomic mass unit-hartree relationship"; break;
                            case 14:  lookupstring ="atomic mass unit-hertz relationship"; break;
                            case 15:  lookupstring ="atomic mass unit-inverse meter relationship"; break;
                            case 16:  lookupstring ="atomic mass unit-joule relationship"; break;
                            case 17:  lookupstring ="atomic mass unit-kelvin relationship"; break;
                            case 18:  lookupstring ="atomic mass unit-kilogram relationship"; break;
                            case 19:  lookupstring ="atomic unit of 1st hyperpolarizability"; break;
                            case 20:  lookupstring ="atomic unit of 2nd hyperpolarizability"; break;
                            case 21:  lookupstring ="atomic unit of action"; break;
                            case 22:  lookupstring ="atomic unit of charge"; break;
                            case 23:  lookupstring ="atomic unit of charge density"; break;
                            case 24:  lookupstring ="atomic unit of current"; break;
                            case 25:  lookupstring ="atomic unit of electric dipole mom."; break;
                            case 26:  lookupstring ="atomic unit of electric field"; break;
                            case 27:  lookupstring ="atomic unit of electric field gradient"; break;
                            case 28:  lookupstring ="atomic unit of electric polarizability"; break;
                            case 29:  lookupstring ="atomic unit of electric potential"; break;
                            case 30:  lookupstring ="atomic unit of electric quadrupole mom."; break;
                            case 31:  lookupstring ="atomic unit of energy"; break;
                            case 32:  lookupstring ="atomic unit of force"; break;
                            case 33:  lookupstring ="atomic unit of length"; break;
                            case 34:  lookupstring ="atomic unit of mag. dipole mom."; break;
                            case 35: lookupstring ="atomic unit of mag. flux density"; break;
                            case 36:  lookupstring ="atomic unit of magnetizability"; break;
                            case 37:  lookupstring ="atomic unit of mass"; break;
                            case 38:  lookupstring ="atomic unit of mom.um"; break;
                            case 39:  lookupstring ="atomic unit of permittivity"; break;
                            case 40:  lookupstring ="atomic unit of time"; break;
                            case 41:  lookupstring ="atomic unit of velocity"; break;
                            case 42:  lookupstring ="Avogadro constant"; break;
                            case 43:  lookupstring ="Bohr magneton"; break;
                            case 44:  lookupstring ="Bohr magneton in eV/T"; break;
                            case 45:  lookupstring ="Bohr magneton in Hz/T"; break;
                            case 46:  lookupstring ="Bohr magneton in inverse meters per tesla"; break;
                            case 47:  lookupstring ="Bohr magneton in K/T"; break;
                            case 48:  lookupstring ="Bohr radius"; break;
                            case 49:  lookupstring ="Boltzmann constant"; break;
                            case 50:  lookupstring ="Boltzmann constant in eV/K"; break;
                            case 51:  lookupstring ="Boltzmann constant in Hz/K"; break;
                            case 52:  lookupstring ="Boltzmann constant in inverse meters per kelvin"; break;
                            case 53:  lookupstring ="characteristic impedance of vacuum"; break;
                            case 54:  lookupstring ="classical electron radius"; break;
                            case 55:  lookupstring ="Compton wavelength"; break;
                            case 56:  lookupstring ="Compton wavelength over 2 pi"; break;
                            case 57:  lookupstring ="conductance quantum"; break;
                            case 58:  lookupstring ="conventional value of Josephson constant"; break;
                            case 59:  lookupstring ="conventional value of von Klitzing constant"; break;
                            case 60:  lookupstring ="Cu x unit"; break;
                            case 61:  lookupstring ="deuteron-electron mag. mom. ratio"; break;
                            case 62:  lookupstring ="deuteron-electron mass ratio"; break;
                            case 63:  lookupstring ="deuteron g factor"; break;
                            case 64:  lookupstring ="deuteron mag. mom."; break;
                            case 65:  lookupstring ="deuteron mag. mom. to Bohr magneton ratio"; break;
                            case 66:  lookupstring ="deuteron mag. mom. to nuclear magneton ratio"; break;
                            case 67:  lookupstring ="deuteron mass"; break;
                            case 68:  lookupstring ="deuteron mass energy equivalent"; break;
                            case 69:  lookupstring ="deuteron mass energy equivalent in MeV"; break;
                            case 70:  lookupstring ="deuteron mass in u"; break;
                            case 71:  lookupstring ="deuteron molar mass"; break;
                            case 72:  lookupstring ="deuteron-neutron mag. mom. ratio"; break;
                            case 73:  lookupstring ="deuteron-proton mag. mom. ratio"; break;
                            case 74:  lookupstring ="deuteron-proton mass ratio"; break;
                            case 75:  lookupstring ="deuteron rms charge radius"; break;
                            case 76:  lookupstring ="electric constant"; break;
                            case 77:  lookupstring ="electron charge to mass quotient"; break;
                            case 78:  lookupstring ="electron-deuteron mag. mom. ratio"; break;
                            case 79:  lookupstring ="electron-deuteron mass ratio"; break;
                            case 80:  lookupstring ="electron g factor"; break;
                            case 81:  lookupstring ="electron gyromag. ratio"; break;
                            case 82:  lookupstring ="electron gyromag. ratio over 2 pi"; break;
                            case 83:  lookupstring ="electron-helion mass ratio"; break;
                            case 84:  lookupstring ="electron mag. mom."; break;
                            case 85:  lookupstring ="electron mag. mom. anomaly"; break;
                            case 86:  lookupstring ="electron mag. mom. to Bohr magneton ratio"; break;
                            case 87:  lookupstring ="electron mag. mom. to nuclear magneton ratio"; break;
                            case 88:  lookupstring ="electron mass"; break;
                            case 89:  lookupstring ="electron mass energy equivalent"; break;
                            case 90:  lookupstring ="electron mass energy equivalent in MeV"; break;
                            case 91:  lookupstring ="electron mass in u"; break;
                            case 92:  lookupstring ="electron molar mass"; break;
                            case 93:  lookupstring ="electron-muon mag. mom. ratio"; break;
                            case 94:  lookupstring ="electron-muon mass ratio"; break;
                            case 95:  lookupstring ="electron-neutron mag. mom. ratio"; break;
                            case 96:  lookupstring ="electron-neutron mass ratio"; break;
                            case 97:  lookupstring ="electron-proton mag. mom. ratio"; break;
                            case 98:  lookupstring ="electron-proton mass ratio"; break;
                            case 99:  lookupstring ="electron-tau mass ratio"; break;
                            case 100:  lookupstring ="electron to alpha particle mass ratio"; break;
                            case 100+1:  lookupstring ="electron to shielded helion mag. mom. ratio"; break;
                            case 101+1:  lookupstring ="electron to shielded proton mag. mom. ratio"; break;
                            case 102+1:  lookupstring ="electron-triton mass ratio"; break;
                            case 103+1:  lookupstring ="electron volt"; break;
                            case 104+1:  lookupstring ="electron volt-atomic mass unit relationship"; break;
                            case 105+1:  lookupstring ="electron volt-hartree relationship"; break;
                            case 106+1:  lookupstring ="electron volt-hertz relationship"; break;
                            case 107+1:  lookupstring ="electron volt-inverse meter relationship"; break;
                            case 108+1:  lookupstring ="electron volt-joule relationship"; break;
                            case 109+1:  lookupstring ="electron volt-kelvin relationship"; break;
                            case 110+1:  lookupstring ="electron volt-kilogram relationship"; break;
                            case 111+1:  lookupstring ="elementary charge"; break;
                            case 112+1:  lookupstring ="elementary charge over h"; break;
                            case 113+1:  lookupstring ="Faraday constant"; break;
                            case 114+1:  lookupstring ="Faraday constant for conventional electric current"; break;
                            case 115+1:  lookupstring ="Fermi coupling constant"; break;
                            case 116+1:  lookupstring ="fine-structure constant"; break;
                            case 117 +1:  lookupstring ="first radiation constant"; break;
                            case 118+1:  lookupstring ="first radiation constant for spectral radiance"; break;
                            case 119+1:  lookupstring ="hartree-atomic mass unit relationship"; break;
                            case 120+1:  lookupstring ="hartree-electron volt relationship"; break;
                            case 121+1:  lookupstring ="Hartree energy"; break;
                            case 122+1:  lookupstring ="Hartree energy in eV"; break;
                            case 123+1:  lookupstring ="hartree-hertz relationship"; break;
                            case 124+1:  lookupstring ="hartree-inverse meter relationship"; break;
                            case 125+1:  lookupstring ="hartree-joule relationship"; break;
                            case 126+1:  lookupstring ="hartree-kelvin relationship"; break;
                            case 127+1:  lookupstring ="hartree-kilogram relationship"; break;
                            case 128+1:  lookupstring ="helion-electron mass ratio"; break;
                            case 129+1:  lookupstring ="helion g factor"; break;
                            case 130+1:  lookupstring ="helion mag. mom."; break;
                            case 131+1:  lookupstring ="helion mag. mom. to Bohr magneton ratio"; break;
                            case 132+1:  lookupstring ="helion mag. mom. to nuclear magneton ratio"; break;
                            case 133+1:  lookupstring ="helion mass"; break;
                            case 134+1:  lookupstring ="helion mass energy equivalent"; break;
                            case 135+1:  lookupstring ="helion mass energy equivalent in MeV"; break;
                            case 136+1:  lookupstring ="helion mass in u"; break;
                            case 137+1:  lookupstring ="helion molar mass"; break;
                            case 138+1:  lookupstring ="helion-proton mass ratio"; break;
                            case 139+1:  lookupstring ="hertz-atomic mass unit relationship"; break;
                            case 140+1:  lookupstring ="hertz-electron volt relationship"; break;
                            case 141+1:  lookupstring ="hertz-hartree relationship"; break;
                            case 142+1:  lookupstring ="hertz-inverse meter relationship"; break;
                            case 143+1:  lookupstring ="hertz-joule relationship"; break;
                            case 144+1:  lookupstring ="hertz-kelvin relationship"; break;
                            case 145+1:  lookupstring ="hertz-kilogram relationship"; break;
                            case 146+1:  lookupstring ="inverse fine-structure constant"; break;
                            case 147+1:  lookupstring ="inverse meter-atomic mass unit relationship"; break;
                            case 148+1:  lookupstring ="inverse meter-electron volt relationship"; break;
                            case 149+1:  lookupstring ="inverse meter-hartree relationship"; break;
                            case 150+1:  lookupstring ="inverse meter-hertz relationship"; break;
                            case 151+1:  lookupstring ="inverse meter-joule relationship"; break;
                            case 152+1:  lookupstring ="inverse meter-kelvin relationship"; break;
                            case 153+1:  lookupstring ="inverse meter-kilogram relationship"; break;
                            case 154+1:  lookupstring ="inverse of conductance quantum"; break;
                            case 155+1:  lookupstring ="Josephson constant"; break;
                            case 156+1:  lookupstring ="joule-atomic mass unit relationship"; break;
                            case 157+1:  lookupstring ="joule-electron volt relationship"; break;
                            case 158+1:  lookupstring ="joule-hartree relationship"; break;
                            case 159+1:  lookupstring ="joule-hertz relationship"; break;
                            case 160+1:  lookupstring ="joule-inverse meter relationship"; break;
                            case 161+1:  lookupstring ="joule-kelvin relationship"; break;
                            case 162+1:  lookupstring ="joule-kilogram relationship"; break;
                            case 163+1:  lookupstring ="kelvin-atomic mass unit relationship"; break;
                            case 164+1:  lookupstring ="kelvin-electron volt relationship"; break;
                            case 165+1:  lookupstring ="kelvin-hartree relationship"; break;
                            case 166+1:  lookupstring ="kelvin-hertz relationship"; break;
                            case 167+1:  lookupstring ="kelvin-inverse meter relationship"; break;
                            case 168+1:  lookupstring ="kelvin-joule relationship"; break;
                            case 169+1:  lookupstring ="kelvin-kilogram relationship"; break;
                            case 170+1:  lookupstring ="kilogram-atomic mass unit relationship"; break;
                            case 171+1:  lookupstring ="kilogram-electron volt relationship"; break;
                            case 172+1:  lookupstring ="kilogram-hartree relationship"; break;
                            case 173+1:  lookupstring ="kilogram-hertz relationship"; break;
                            case 174+1:  lookupstring ="kilogram-inverse meter relationship"; break;
                            case 175+1:  lookupstring ="kilogram-joule relationship"; break;
                            case 176+1:  lookupstring ="kilogram-kelvin relationship"; break;
                            case 177+1:  lookupstring ="lattice parameter of silicon"; break;
                            case 178+1:  lookupstring ="Loschmidt constant (273.15 K, 100 kPa)"; break;
                            case 179+1:  lookupstring ="Loschmidt constant (273.15 K, 101.325 kPa)"; break;
                            case 180+1:  lookupstring ="mag. constant"; break;
                            case 181+1:  lookupstring ="mag. flux quantum"; break;
                            case 182+1:  lookupstring ="molar gas constant"; break;
                            case 183+1:  lookupstring ="molar mass constant"; break;
                            case 184+1:  lookupstring ="molar mass of carbon-12"; break;
                            case 185+1:  lookupstring ="molar Planck constant"; break;
                            case 186+1:  lookupstring ="molar Planck constant times c"; break;
                            case 187+1:  lookupstring ="molar volume of ideal gas (273.15 K, 100 kPa)"; break;
                            case 188+1:  lookupstring ="molar volume of ideal gas (273.15 K, 101.325 kPa)"; break;
                            case 189+1:  lookupstring ="molar volume of silicon"; break;
                            case 190+1:  lookupstring ="Mo x unit"; break;
                            case 191+1:  lookupstring ="muon Compton wavelength"; break;
                            case 192+1:  lookupstring ="muon Compton wavelength over 2 pi"; break;
                            case 193+1:  lookupstring ="muon-electron mass ratio"; break;
                            case 194+1:  lookupstring ="muon g factor"; break;
                            case 195+1:  lookupstring ="muon mag. mom."; break;
                            case 196+1:  lookupstring ="muon mag. mom. anomaly"; break;
                            case 197+1:  lookupstring ="muon mag. mom. to Bohr magneton ratio"; break;
                            case 198+1:  lookupstring ="muon mag. mom. to nuclear magneton ratio"; break;
                            case 199+1:  lookupstring ="muon mass"; break;
                            case 200+1:  lookupstring ="muon mass energy equivalent"; break;
                            case 201+1:  lookupstring ="muon mass energy equivalent in MeV"; break;
                            case 202+1:  lookupstring ="muon mass in u"; break;
                            case 203+1:  lookupstring ="muon molar mass"; break;
                            case 204+1:  lookupstring ="muon-neutron mass ratio"; break;
                            case 205+1:  lookupstring ="muon-proton mag. mom. ratio"; break;
                            case 206+1:  lookupstring ="muon-proton mass ratio"; break;
                            case 207+1:  lookupstring ="muon-tau mass ratio"; break;
                            case 208+1:  lookupstring ="natural unit of action"; break;
                            case 209+1:  lookupstring ="natural unit of action in eV s"; break;
                            case 210+1:  lookupstring ="natural unit of energy"; break;
                            case 211+1:  lookupstring ="natural unit of energy in MeV"; break;
                            case 212+1:  lookupstring ="natural unit of length"; break;
                            case 213+1:  lookupstring ="natural unit of mass"; break;
                            case 214+1:  lookupstring ="natural unit of mom.um"; break;
                            case 215+1:  lookupstring ="natural unit of mom.um in MeV/c"; break;
                            case 216+1:  lookupstring ="natural unit of time"; break;
                            case 217+1:  lookupstring ="natural unit of velocity"; break;
                            case 218+1:  lookupstring ="neutron Compton wavelength"; break;
                            case 219+1:  lookupstring ="neutron Compton wavelength over 2 pi"; break;
                            case 220+1:  lookupstring ="neutron-electron mag. mom. ratio"; break;
                            case 221+1:  lookupstring ="neutron-electron mass ratio"; break;
                            case 222+1:  lookupstring ="neutron g factor"; break;
                            case 223+1:  lookupstring ="neutron gyromag. ratio"; break;
                            case 224+1:  lookupstring ="neutron gyromag. ratio over 2 pi"; break;
                            case 225+1:  lookupstring ="neutron mag. mom."; break;
                            case 226+1:  lookupstring ="neutron mag. mom. to Bohr magneton ratio"; break;
                            case 227+1:  lookupstring ="neutron mag. mom. to nuclear magneton ratio"; break;
                            case 228+1:  lookupstring ="neutron mass"; break;
                            case 229+1:  lookupstring ="neutron mass energy equivalent"; break;
                            case 230+1:  lookupstring ="neutron mass energy equivalent in MeV"; break;
                            case 231+1:  lookupstring ="neutron mass in u"; break;
                            case 232+1:  lookupstring ="neutron molar mass"; break;
                            case 233+1:  lookupstring ="neutron-muon mass ratio"; break;
                            case 234+1:  lookupstring ="neutron-proton mag. mom. ratio"; break;
                            case 235+1:  lookupstring ="neutron-proton mass difference"; break;
                            case 236+1:  lookupstring ="neutron-proton mass difference energy equivalent"; break;
                            case 237+1:  lookupstring ="neutron-proton mass difference energy equivalent in MeV"; break;
                            case 238+1:  lookupstring ="neutron-proton mass difference in u"; break;
                            case 239+1:  lookupstring ="neutron-proton mass ratio"; break;
                            case 240+1:  lookupstring ="neutron-tau mass ratio"; break;
                            case 241+1:  lookupstring ="neutron to shielded proton mag. mom. ratio"; break;
                            case 242+1:  lookupstring ="Newtonian constant of gravitation"; break;
                            case 243+1:  lookupstring ="Newtonian constant of gravitation over h-bar c"; break;
                            case 244+1:  lookupstring ="nuclear magneton"; break;
                            case 245+1:  lookupstring ="nuclear magneton in eV/T"; break;
                            case 246+1:  lookupstring ="nuclear magneton in inverse meters per tesla"; break;
                            case 247+1:  lookupstring ="nuclear magneton in K/T"; break;
                            case 248+1:  lookupstring ="nuclear magneton in MHz/T"; break;
                            case 249+1:  lookupstring ="Planck constant"; break;
                            case 250+1:  lookupstring ="Planck constant in eV s"; break;
                            case 251+1:  lookupstring ="Planck constant over 2 pi"; break;
                            case 252+1:  lookupstring ="Planck constant over 2 pi in eV s"; break;
                            case 253+1:  lookupstring ="Planck constant over 2 pi times c in MeV fm"; break;
                            case 254+1:  lookupstring ="Planck length"; break;
                            case 255+1:  lookupstring ="Planck mass"; break;
                            case 256+1:  lookupstring ="Planck mass energy equivalent in GeV"; break;
                            case 257+1:  lookupstring ="Planck temperature"; break;
                            case 258+1:  lookupstring ="Planck time"; break;
                            case 259+1:  lookupstring ="proton charge to mass quotient"; break;
                            case 260+1:  lookupstring ="proton Compton wavelength"; break;
                            case 261+1:  lookupstring ="proton Compton wavelength over 2 pi"; break;
                            case 262+1:  lookupstring ="proton-electron mass ratio"; break;
                            case 263+1:  lookupstring ="proton g factor"; break;
                            case 264+1:  lookupstring ="proton gyromag. ratio"; break;
                            case 265+1:  lookupstring ="proton gyromag. ratio over 2 pi"; break;
                            case 266+1:  lookupstring ="proton mag. mom."; break;
                            case 267+1:  lookupstring ="proton mag. mom. to Bohr magneton ratio"; break;
                            case 268+1:  lookupstring ="proton mag. mom. to nuclear magneton ratio"; break;
                            case 269+1:  lookupstring ="proton mag. shielding correction"; break;
                            case 270+1:  lookupstring ="proton mass"; break;
                            case 271+1:  lookupstring ="proton mass energy equivalent"; break;
                            case 272+1:  lookupstring ="proton mass energy equivalent in MeV"; break;
                            case 273+1:  lookupstring ="proton mass in u"; break;
                            case 274+1:  lookupstring ="proton molar mass"; break;
                            case 275+1:  lookupstring ="proton-muon mass ratio"; break;
                            case 276+1:  lookupstring ="proton-neutron mag. mom. ratio"; break;
                            case 277+1:  lookupstring ="proton-neutron mass ratio"; break;
                            case 278+1:  lookupstring ="proton rms charge radius"; break;
                            case 279+1:  lookupstring ="proton-tau mass ratio"; break;
                            case 280+1:  lookupstring ="quantum of circulation"; break;
                            case 281+1:  lookupstring ="quantum of circulation times 2"; break;
                            case 282+1:  lookupstring ="Rydberg constant"; break;
                            case 283+1:  lookupstring ="Rydberg constant times c in Hz"; break;
                            case 284+1:  lookupstring ="Rydberg constant times hc in eV"; break;
                            case 285+1:  lookupstring ="Rydberg constant times hc in J"; break;
                            case 286+1:  lookupstring ="Sackur-Tetrode constant (1 K, 100 kPa)"; break;
                            case 287+1:  lookupstring ="Sackur-Tetrode constant (1 K, 101.325 kPa)"; break;
                            case 288+1:  lookupstring ="second radiation constant"; break;
                            case 289+1:  lookupstring ="shielded helion gyromag. ratio"; break;
                            case 290+1:  lookupstring ="shielded helion gyromag. ratio over 2 pi"; break;
                            case 291+1:  lookupstring ="shielded helion mag. mom."; break;
                            case 292+1:  lookupstring ="shielded helion mag. mom. to Bohr magneton ratio"; break;
                            case 293+1:  lookupstring ="shielded helion mag. mom. to nuclear magneton ratio"; break;
                            case 294+1:  lookupstring ="shielded helion to proton mag. mom. ratio"; break;
                            case 295+1:  lookupstring ="shielded helion to shielded proton mag. mom. ratio"; break;
                            case 296+1:  lookupstring ="shielded proton gyromag. ratio"; break;
                            case 297+1:  lookupstring ="shielded proton gyromag. ratio over 2 pi"; break;
                            case 298+1:  lookupstring ="shielded proton mag. mom."; break;
                            case 299+1:  lookupstring ="shielded proton mag. mom. to Bohr magneton ratio"; break;
                            case 300+1:  lookupstring ="shielded proton mag. mom. to nuclear magneton ratio"; break;
                            case 301+1:  lookupstring ="speed of light in vacuum"; break;
                            case 302+1:  lookupstring ="standard acceleration of gravity"; break;
                            case 303+1:  lookupstring ="standard atmosphere"; break;
                            case 304+1:  lookupstring ="standard-state pressure"; break;
                            case 305+1:  lookupstring ="Stefan-Boltzmann constant"; break;
                            case 306+1:  lookupstring ="tau Compton wavelength"; break;
                            case 307+1:  lookupstring ="tau Compton wavelength over 2 pi"; break;
                            case 308+1:  lookupstring ="tau-electron mass ratio"; break;
                            case 309+1:  lookupstring ="tau mass"; break;
                            case 310+1:  lookupstring ="tau mass energy equivalent"; break;
                            case 311+1:  lookupstring ="tau mass energy equivalent in MeV"; break;
                            case 312+1:  lookupstring ="tau mass in u"; break;
                            case 313+1:  lookupstring ="tau molar mass"; break;
                            case 314+1:  lookupstring ="tau-muon mass ratio"; break;
                            case 315+1:  lookupstring ="tau-neutron mass ratio"; break;
                            case 316+1:  lookupstring ="tau-proton mass ratio"; break;
                            case 317+1:  lookupstring ="Thomson cross section"; break;
                            case 318+1:  lookupstring ="triton-electron mass ratio"; break;
                            case 319+1:  lookupstring ="triton g factor"; break;
                            case 320+1:  lookupstring ="triton mag. mom."; break;
                            case 321+1:  lookupstring ="triton mag. mom. to Bohr magneton ratio"; break;
                            case 322+1:  lookupstring ="triton mag. mom. to nuclear magneton ratio"; break;
                            case 323+1:  lookupstring ="triton mass"; break;
                            case 324+1:  lookupstring ="triton mass energy equivalent"; break;
                            case 325+1:  lookupstring ="triton mass energy equivalent in MeV"; break;
                            case 326+1:  lookupstring ="triton mass in u"; break;
                            case 327+1:  lookupstring ="triton molar mass"; break;
                            case 328+1:  lookupstring ="triton-proton mass ratio"; break;
                            case 329+1:  lookupstring ="unified atomic mass unit"; break;
                            case 330+1:  lookupstring ="von Klitzing constant"; break;
                            case 331+1:  lookupstring ="weak mixing angle"; break;
                            case 332+1:  lookupstring ="Wien frequency displacement law constant"; break;
                            case 333+1:  lookupstring ="Wien wavelength displacement law constant"; break;

                        }

                        Firebase ref = new Firebase(FirebasePath);

                        Query queryRef = ref.orderByChild("Quantity ").equalTo(lookupstring);

                        queryRef.addChildEventListener(new ChildEventListener() {
                            public void onChildAdded(DataSnapshot snapshot, String previousChild) {
                                Map<String,String> outputarray = (Map)snapshot.getValue();

                                textView2.setText("");

                                for ( Map.Entry<String, String> entry : outputarray.entrySet()) {
                                    String key = entry.getKey();
                                    String value = entry.getValue();

                                    textView2.append(key + "=" + value);
                                    textView2.append("\n");
                                }

                                textView2.setMovementMethod(new ScrollingMovementMethod());
                                System.out.println(outputarray);
                            }

                            public void onChildRemoved(DataSnapshot snapshot) {

                            }

                            public void onChildChanged(DataSnapshot snapshot, String s) {

                            }

                            public void onChildMoved(DataSnapshot snapshot, String s) {

                            }

                            public void onCancelled(FirebaseError error) {

                            }
                        });


                    }

                });


            }

            @Override
            public boolean onCreateOptionsMenu(Menu menu) {
                // Inflate the menu; this adds items to the action bar if it is present.
                getMenuInflater().inflate(R.menu.menu_constants_button, menu);
                return true;
            }

            @Override
            public boolean onOptionsItemSelected(MenuItem item) {
                // Handle action bar item clicks here. The action bar will
                // automatically handle clicks on the Home/Up button, so long
                // as you specify a parent activity in AndroidManifest.xml.
                int id = item.getItemId();

                //noinspection SimplifiableIfStatement
                if (id == R.id.action_settings) {
                    return true;
                }

                return super.onOptionsItemSelected(item);
            }
        }
